### ISSUE TITLE
Cannot delete user

### ISSUE THREAD

**Issue by alepocalypse** [PagerDuty/public-support-scripts#16]
Traceback (most recent call last):
  File "./user_deprovision.py", line 520, in <module>
    main(args)
  File "./user_deprovision.py", line 467, in main
    args.prompt_del, args.auto_resolve, args.backup)
  File "./user_deprovision.py", line 327, in delete_user
    escalation_policies[e]['id'],
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by Deconstrained** [comment]
Hi @alepocalypse sorry for the delay in getting back to you, but this looks like it was for an older version of the script.

The latest version that is maintained in this repository is a very heavily refactored version that is actually shorter than 520 lines, so I am not sure exactly what the analogous line would be in this version or if the issue is still applicable. 

Can you please let me know if you can confirm the issue persists in the latest version, or if you run into any other issues? If so, feel free to open up a new issue.
